export const DATA_FETCHED = 'DATA_FETCHED';
export const DATA_SUCCEEDED = 'DATA_SUCCEEDED';
export const DATA_FAILED = 'DATA_FAILED';
export const SUGGEST_ACTIVATED = 'SUGGEST_ACTIVATED';
export const SUGGEST_INPUT_CHANGED = 'SUGGEST_INPUT_CHANGED';
export const SELECT_SUGGESTED = 'SELECT_SUGGESTED';
export const REQUEST_SUGGESTED_PLACES = 'RETRIEVE_SUGGESTED_PLACES';
export const RECEIVE_SUGGESTED_PLACES = 'RECEIVE_SUGGESTED_PLACES';
